'use client';

import { useState } from 'react';

const ADMIN_PASSWORD = 'loxy-admin-2024';

type InputType = 'none' | 'text' | 'phone' | 'choice';
type Style = 'sheet' | 'banner' | 'fullscreen';

interface Choice {
  label: string;
  value: string;
}

interface FormState {
  key: string;
  title: string;
  body: string;
  icon: string;
  ctaLabel: string;
  dismissLabel: string;
  inputType: InputType;
  choices: Choice[];
  style: Style;
  required: boolean;
  priority: number;
  // Targeting
  targetUserIds: string;
  targetCircleIds: string;
  targetPlatform: '' | 'ios' | 'android';
  targetMinVersion: string;
  expiresIn: '' | '24h' | '3d' | '7d' | '30d' | 'never';
}

const DEFAULT_FORM: FormState = {
  key: '',
  title: '',
  body: '',
  icon: '',
  ctaLabel: 'Got it',
  dismissLabel: '',
  inputType: 'none',
  choices: [{ label: '', value: '' }],
  style: 'sheet',
  required: true,
  priority: 0,
  targetUserIds: '',
  targetCircleIds: '',
  targetPlatform: '',
  targetMinVersion: '',
  expiresIn: '7d',
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function sqlLiteral(value: string | null): string {
  if (value === null) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function uuidArray(raw: string): string {
  const ids = raw
    .split(/[\s,]+/)
    .map((s) => s.trim())
    .filter(Boolean);
  if (ids.length === 0) return 'null';
  return `'{${ids.join(',')}}'::uuid[]`;
}

function expiresClause(expiresIn: string): string {
  const map: Record<string, string> = {
    '24h': "now() + interval '24 hours'",
    '3d': "now() + interval '3 days'",
    '7d': "now() + interval '7 days'",
    '30d': "now() + interval '30 days'",
    never: 'null',
    '': 'null',
  };
  return map[expiresIn] ?? 'null';
}

function generateSQL(f: FormState): string {
  const key = f.key || slugify(f.title) || 'prompt_key';
  const dismissLabel = f.dismissLabel.trim() || null;
  const platform = f.targetPlatform || null;
  const minVersion = f.targetMinVersion.trim() || null;
  const userIds = uuidArray(f.targetUserIds);
  const circleIds = uuidArray(f.targetCircleIds);

  let choicesJson = 'null';
  if (f.inputType === 'choice' && f.choices.some((c) => c.label)) {
    const valid = f.choices.filter((c) => c.label.trim());
    choicesJson = `'${JSON.stringify(
      valid.map((c) => ({ label: c.label, value: c.value || slugify(c.label) }))
    )}'::jsonb`;
  }

  const lines = [
    `-- ── App Prompt: ${key} ${'─'.repeat(Math.max(0, 60 - key.length))}`,
    `-- Generated by Loxymity Prompt Builder · ${new Date().toISOString().slice(0, 10)}`,
    `-- Paste into: Supabase Dashboard → SQL Editor → Run`,
    ``,
    `insert into public.app_prompts (`,
    `  key, title, body, icon,`,
    `  cta_label, dismiss_label,`,
    `  input_type, choices,`,
    `  style, required, priority,`,
    `  target_user_ids, target_circle_ids,`,
    `  target_geofence_ids,`,
    `  target_geo_lat, target_geo_lng, target_geo_radius_m,`,
    `  target_min_version, target_platform,`,
    `  expires_at`,
    `) values (`,
    `  ${sqlLiteral(key)},`,
    `  ${sqlLiteral(f.title)},`,
    `  ${sqlLiteral(f.body)},`,
    `  ${sqlLiteral(f.icon.trim() || null)},`,
    `  ${sqlLiteral(f.ctaLabel || 'OK')},`,
    `  ${sqlLiteral(dismissLabel)},`,
    `  ${sqlLiteral(f.inputType)},`,
    `  ${choicesJson},`,
    `  ${sqlLiteral(f.style)},`,
    `  ${f.required ? 'true' : 'false'},`,
    `  ${f.priority},`,
    `  -- Targeting (null = no restriction on that axis)`,
    `  ${userIds},   -- target_user_ids`,
    `  ${circleIds}, -- target_circle_ids`,
    `  null,         -- target_geofence_ids (set manually if needed)`,
    `  null, null, null, -- geo lat/lng/radius (set manually if needed)`,
    `  ${sqlLiteral(minVersion)},`,
    `  ${sqlLiteral(platform)},`,
    `  ${expiresClause(f.expiresIn)}`,
    `);`,
    ``,
    `-- To retract before it expires:`,
    `-- delete from public.app_prompts where key = ${sqlLiteral(key)};`,
  ];

  return lines.join('\n');
}

export default function PromptBuilderPage() {
  const [authed, setAuthed] = useState(false);
  const [password, setPassword] = useState('');
  const [pwError, setPwError] = useState('');

  const [form, setForm] = useState<FormState>(DEFAULT_FORM);
  const [copied, setCopied] = useState(false);

  function handleGate() {
    if (password === ADMIN_PASSWORD) {
      setAuthed(true);
      setPwError('');
    } else {
      setPwError('Incorrect admin password.');
    }
  }

  function set<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function setChoice(index: number, field: keyof Choice, value: string) {
    setForm((prev) => {
      const choices = [...prev.choices];
      choices[index] = { ...choices[index], [field]: value };
      return { ...prev, choices };
    });
  }

  function addChoice() {
    setForm((prev) => ({ ...prev, choices: [...prev.choices, { label: '', value: '' }] }));
  }

  function removeChoice(index: number) {
    setForm((prev) => ({ ...prev, choices: prev.choices.filter((_, i) => i !== index) }));
  }

  const sql = generateSQL(form);

  async function handleCopy() {
    await navigator.clipboard.writeText(sql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleReset() {
    setForm(DEFAULT_FORM);
    setCopied(false);
  }

  // ── Password gate ──────────────────────────────────────────────────────────
  if (!authed) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center px-4">
        <div className="bg-white rounded-3xl p-8 w-full max-w-sm shadow-2xl">
          <div className="text-center mb-8">
            <p className="text-2xl font-black text-gray-900">Loxymity</p>
            <p className="text-gray-500 text-sm mt-1">Prompt Builder</p>
          </div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Admin password</label>
          <input
            type="password"
            className="w-full border border-gray-200 rounded-xl px-4 py-3 text-sm mb-3 focus:outline-none focus:ring-2 focus:ring-primary"
            placeholder="Enter admin password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleGate()}
          />
          {pwError && <p className="text-red-500 text-xs mb-3">{pwError}</p>}
          <button
            onClick={handleGate}
            className="w-full bg-primary hover:bg-primary-dark text-white font-semibold py-3 rounded-xl transition-colors"
          >
            Continue
          </button>
          <p className="text-center mt-4">
            <a href="/admin" className="text-xs text-gray-400 hover:text-gray-600 transition-colors">← Admin dashboard</a>
          </p>
        </div>
      </div>
    );
  }

  // ── Main builder ───────────────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-100 px-6 py-4 flex items-center justify-between">
        <div>
          <p className="font-black text-gray-900 text-lg">Prompt Builder</p>
          <p className="text-gray-400 text-xs">Generate SQL to push in-app modals &amp; banners to users</p>
        </div>
        <div className="flex items-center gap-4">
          <a href="/admin" className="text-sm text-gray-500 hover:text-gray-900 transition-colors">← Admin</a>
          <a href="/" className="text-sm text-gray-500 hover:text-gray-900 transition-colors">← Site</a>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">

          {/* ── Left: form ── */}
          <div className="space-y-6">

            {/* Content */}
            <section className="bg-white rounded-2xl border border-gray-100 p-6">
              <h2 className="font-semibold text-gray-900 mb-4">Content</h2>
              <div className="space-y-4">

                <div className="grid grid-cols-4 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-gray-500 mb-1">Icon (emoji)</label>
                    <input
                      type="text"
                      className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary text-center text-xl"
                      placeholder="📢"
                      maxLength={2}
                      value={form.icon}
                      onChange={(e) => set('icon', e.target.value)}
                    />
                  </div>
                  <div className="col-span-3">
                    <label className="block text-xs font-medium text-gray-500 mb-1">Title <span className="text-red-400">*</span></label>
                    <input
                      type="text"
                      className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                      placeholder="Important Update"
                      value={form.title}
                      onChange={(e) => set('title', e.target.value)}
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Body <span className="text-red-400">*</span></label>
                  <textarea
                    rows={3}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                    placeholder="We've updated our privacy policy. Please review and accept to continue."
                    value={form.body}
                    onChange={(e) => set('body', e.target.value)}
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Prompt key <span className="text-gray-400 font-normal">(auto-filled from title, must be unique)</span>
                  </label>
                  <input
                    type="text"
                    className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary"
                    placeholder="privacy_update_jun2026"
                    value={form.key}
                    onChange={(e) => set('key', e.target.value)}
                    onBlur={() => {
                      if (!form.key && form.title) set('key', slugify(form.title));
                    }}
                  />
                  {!form.key && form.title && (
                    <button
                      onClick={() => set('key', slugify(form.title))}
                      className="text-xs text-primary hover:underline mt-1"
                    >
                      Use &ldquo;{slugify(form.title)}&rdquo;
                    </button>
                  )}
                </div>

              </div>
            </section>

            {/* Buttons & input */}
            <section className="bg-white rounded-2xl border border-gray-100 p-6">
              <h2 className="font-semibold text-gray-900 mb-4">Buttons &amp; Input</h2>
              <div className="space-y-4">

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-gray-500 mb-1">CTA label</label>
                    <input
                      type="text"
                      className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                      placeholder="Got it"
                      value={form.ctaLabel}
                      onChange={(e) => set('ctaLabel', e.target.value)}
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-500 mb-1">Dismiss label <span className="text-gray-400 font-normal">(blank = no skip)</span></label>
                    <input
                      type="text"
                      className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                      placeholder="Maybe later"
                      value={form.dismissLabel}
                      onChange={(e) => set('dismissLabel', e.target.value)}
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Input type</label>
                  <div className="flex gap-2 flex-wrap">
                    {(['none', 'text', 'phone', 'choice'] as InputType[]).map((t) => (
                      <button
                        key={t}
                        onClick={() => set('inputType', t)}
                        className={`px-4 py-1.5 rounded-full text-xs font-semibold capitalize transition-colors border ${
                          form.inputType === t
                            ? 'bg-primary text-white border-primary'
                            : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
                        }`}
                      >
                        {t}
                      </button>
                    ))}
                  </div>
                </div>

                {form.inputType === 'choice' && (
                  <div>
                    <label className="block text-xs font-medium text-gray-500 mb-2">Choices</label>
                    <div className="space-y-2">
                      {form.choices.map((c, i) => (
                        <div key={i} className="flex gap-2 items-center">
                          <input
                            type="text"
                            className="flex-1 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                            placeholder="Label"
                            value={c.label}
                            onChange={(e) => setChoice(i, 'label', e.target.value)}
                          />
                          <input
                            type="text"
                            className="w-28 border border-gray-200 rounded-xl px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary"
                            placeholder="value"
                            value={c.value}
                            onChange={(e) => setChoice(i, 'value', e.target.value)}
                          />
                          {form.choices.length > 1 && (
                            <button
                              onClick={() => removeChoice(i)}
                              className="text-gray-300 hover:text-red-400 transition-colors text-lg leading-none"
                            >
                              ×
                            </button>
                          )}
                        </div>
                      ))}
                    </div>
                    <button
                      onClick={addChoice}
                      className="mt-2 text-xs text-primary hover:underline"
                    >
                      + Add choice
                    </button>
                  </div>
                )}

              </div>
            </section>

            {/* Display */}
            <section className="bg-white rounded-2xl border border-gray-100 p-6">
              <h2 className="font-semibold text-gray-900 mb-4">Display</h2>
              <div className="space-y-4">

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Style</label>
                  <div className="flex gap-2">
                    {(['sheet', 'banner', 'fullscreen'] as Style[]).map((s) => (
                      <button
                        key={s}
                        onClick={() => set('style', s)}
                        className={`flex-1 py-2 rounded-xl text-xs font-semibold capitalize transition-colors border ${
                          form.style === s
                            ? 'bg-primary text-white border-primary'
                            : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
                        }`}
                      >
                        {s === 'sheet' ? '⬆️ Sheet' : s === 'banner' ? '📌 Banner' : '🖥️ Fullscreen'}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-gray-500 mb-1">Priority <span className="text-gray-400 font-normal">(higher = first)</span></label>
                    <input
                      type="number"
                      className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                      value={form.priority}
                      onChange={(e) => set('priority', parseInt(e.target.value) || 0)}
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-500 mb-1">Required</label>
                    <div className="flex gap-2 mt-1">
                      {([true, false] as const).map((v) => (
                        <button
                          key={String(v)}
                          onClick={() => set('required', v)}
                          className={`flex-1 py-2 rounded-xl text-xs font-semibold transition-colors border ${
                            form.required === v
                              ? 'bg-primary text-white border-primary'
                              : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
                          }`}
                        >
                          {v ? 'Required' : 'Optional'}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Expires</label>
                  <div className="flex gap-2 flex-wrap">
                    {([
                      { label: '24 h', value: '24h' },
                      { label: '3 days', value: '3d' },
                      { label: '7 days', value: '7d' },
                      { label: '30 days', value: '30d' },
                      { label: 'Never', value: 'never' },
                    ] as { label: string; value: FormState['expiresIn'] }[]).map((opt) => (
                      <button
                        key={opt.value}
                        onClick={() => set('expiresIn', opt.value)}
                        className={`px-4 py-1.5 rounded-full text-xs font-semibold transition-colors border ${
                          form.expiresIn === opt.value
                            ? 'bg-primary text-white border-primary'
                            : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
                        }`}
                      >
                        {opt.label}
                      </button>
                    ))}
                  </div>
                </div>

              </div>
            </section>

            {/* Targeting */}
            <section className="bg-white rounded-2xl border border-gray-100 p-6">
              <h2 className="font-semibold text-gray-900 mb-1">Targeting</h2>
              <p className="text-xs text-gray-400 mb-4">Leave blank to target all users.</p>
              <div className="space-y-4">

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Platform</label>
                  <div className="flex gap-2">
                    {([
                      { label: 'All', value: '' },
                      { label: '🍎 iOS', value: 'ios' },
                      { label: '🤖 Android', value: 'android' },
                    ] as { label: string; value: FormState['targetPlatform'] }[]).map((p) => (
                      <button
                        key={p.value}
                        onClick={() => set('targetPlatform', p.value)}
                        className={`px-4 py-1.5 rounded-full text-xs font-semibold transition-colors border ${
                          form.targetPlatform === p.value
                            ? 'bg-primary text-white border-primary'
                            : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
                        }`}
                      >
                        {p.label}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Min app version</label>
                  <input
                    type="text"
                    className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary"
                    placeholder="0.7.0"
                    value={form.targetMinVersion}
                    onChange={(e) => set('targetMinVersion', e.target.value)}
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Specific user IDs <span className="text-gray-400 font-normal">(comma or newline separated UUIDs)</span>
                  </label>
                  <textarea
                    rows={2}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                    placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    value={form.targetUserIds}
                    onChange={(e) => set('targetUserIds', e.target.value)}
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Circle IDs <span className="text-gray-400 font-normal">(comma or newline separated UUIDs)</span>
                  </label>
                  <textarea
                    rows={2}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                    placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    value={form.targetCircleIds}
                    onChange={(e) => set('targetCircleIds', e.target.value)}
                  />
                </div>

              </div>
            </section>

          </div>

          {/* ── Right: SQL output ── */}
          <div className="lg:sticky lg:top-8 h-fit space-y-4">

            {/* Preview card */}
            <div className="bg-white rounded-2xl border border-gray-100 p-6">
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-3">Preview</p>
              <div className={`rounded-2xl border-2 border-gray-100 p-5 ${form.style === 'banner' ? 'flex items-start gap-3' : 'text-center'}`}>
                {form.icon && (
                  <span className={`text-3xl ${form.style === 'banner' ? '' : 'block mb-2'}`}>{form.icon}</span>
                )}
                <div className={form.style === 'banner' ? 'flex-1 text-left' : ''}>
                  <p className="font-bold text-gray-900 text-base">
                    {form.title || <span className="text-gray-300">Title</span>}
                  </p>
                  <p className="text-gray-500 text-sm mt-1">
                    {form.body || <span className="text-gray-300">Body text will appear here.</span>}
                  </p>
                  {form.inputType === 'text' && (
                    <div className="mt-3 border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-400">Type your answer…</div>
                  )}
                  {form.inputType === 'phone' && (
                    <div className="mt-3 border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-400">+1 (555) 000-0000</div>
                  )}
                  {form.inputType === 'choice' && (
                    <div className="mt-3 space-y-1.5">
                      {form.choices.filter((c) => c.label).map((c, i) => (
                        <div key={i} className="border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-700">{c.label}</div>
                      ))}
                    </div>
                  )}
                  <div className={`mt-4 flex gap-2 ${form.style === 'banner' ? '' : 'justify-center'}`}>
                    <button className="px-4 py-2 bg-primary text-white text-sm font-semibold rounded-xl">
                      {form.ctaLabel || 'OK'}
                    </button>
                    {form.dismissLabel && (
                      <button className="px-4 py-2 bg-gray-100 text-gray-600 text-sm font-semibold rounded-xl">
                        {form.dismissLabel}
                      </button>
                    )}
                  </div>
                </div>
              </div>
            </div>

            {/* SQL output */}
            <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
              <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                <p className="font-semibold text-gray-900">Generated SQL</p>
                <div className="flex gap-2">
                  <button
                    onClick={handleReset}
                    className="px-3 py-1.5 text-xs text-gray-500 hover:text-gray-900 border border-gray-200 rounded-lg transition-colors"
                  >
                    Reset
                  </button>
                  <button
                    onClick={handleCopy}
                    className={`px-4 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
                      copied
                        ? 'bg-emerald-500 text-white'
                        : 'bg-primary hover:bg-primary-dark text-white'
                    }`}
                  >
                    {copied ? '✓ Copied!' : 'Copy SQL'}
                  </button>
                </div>
              </div>
              <pre className="px-6 py-5 text-xs font-mono text-gray-700 bg-gray-50 overflow-x-auto whitespace-pre leading-relaxed">
                {sql}
              </pre>
            </div>

            {/* How to use */}
            <div className="bg-amber-50 border border-amber-100 rounded-2xl p-5">
              <p className="text-xs font-semibold text-amber-800 mb-2">How to publish</p>
              <ol className="text-xs text-amber-700 space-y-1 list-decimal list-inside">
                <li>Copy the SQL above</li>
                <li>Open <strong>Supabase Dashboard → SQL Editor</strong></li>
                <li>Paste and click <strong>Run</strong></li>
                <li>The prompt appears for targeted users on next app open</li>
              </ol>
              <p className="text-xs text-amber-600 mt-3">
                Users who tap the CTA won&apos;t see it again. To retract early, run the <code className="bg-amber-100 px-1 rounded">DELETE</code> comment at the bottom of the SQL.
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
